# Generated by Django 3.2 on 2024-10-27 23:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WordGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="word_groups", to="groups.folder"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("delimiter", models.CharField(max_length=1)),
                ("batch_id", models.UUIDField()),
                ("add_date", models.DateTimeField()),
                (
                    "word_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="words",
                        to="groups.wordgroup",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["batch_id"], name="groups_word_batch_i_d224db_idx"),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["word_group"], name="groups_word_word_gr_a0c5bb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("batch_id", "name")},
        ),
    ]
